
export const BUYER_LOGIN = 'BUYER_LOGIN';
export const SELLER_LOGIN = 'SELLER_LOGIN';
export const ENTER_DASHBOARD = 'ENTER_DASHBOARD';

export const ADD_USER_ADDRESS = 'ADD_USER_ADDRESS';
export const ADD_CONTRACT_ADDRESSES = 'ADD_CONTRACT_ADDRESSES';

export const RESET_LOAD_CONTRACTS_SUCCESS = 'RESET_LOAD_CONTRACTS_SUCCESS';
export const LOAD_CONTRACTS_SUCCESS = 'LOAD_CONTRACTS_SUCCESS';

export const RESET_NEW_CONTRACT = 'RESET_NEW_CONTRACT';
export const SET_NEW_CONTRACT_START_DATE = 'SET_NEW_CONTRACT_START_DATE';
export const SET_NEW_CONTRACT_END_DATE = 'SET_NEW_CONTRACT_END_DATE';
export const SET_NEW_CONTRACT_TERMS = 'SET_NEW_CONTRACT_TERMS';
export const DEPLOY_NEW_CONTRACT = 'DEPLOY_NEW_CONTRACT';
export const ADD_CONTRACT_ABI = 'ADD_CONTRACT_ABI';

export const REQUEST_ADD_KEYSTORE = 'REQUEST_ADD_KEYSTORE';
export const ADD_KEYSTORE = 'ADD_KEYSTORE';
export const SET_TEMPORARY_PRIVATE_KEY = 'SET_TEMPORARY_PRIVATE_KEY';
export const VERIFY_TEMPORARY_PRIVATE_KEY = 'VERIFY_TEMPORARY_PRIVATE_KEY';
export const RESET_TEMPORARY_PRIVATE_KEY = 'RESET_TEMPORARY_PRIVATE_KEY';
export const KEY_VERIFICATION_FAILED = 'KEY_VERIFICATION_FAILED';

export const NOOP_ACTION = 'NOOP_ACTION';

// Contract states
export const ACTIVATE_CONTRACT = 'ACTIVATE_CONTRACT';
export const CANCEL_CONTRACT = 'CANCEL_CONTRACT';
export const REVIEW_CONTRACT = 'REVIEW_CONTRACT';
export const RESOLVE_REVIEW_CONTRACT = 'RESOLVE_REVIEW_CONTRACT';
export const RESOLVE_PENDING_CONTRACT = 'RESOLVE_PENDING_CONTRACT';

export const CONTRACT_CHANGE_START = 'CONTRACT_CHANGE_START';
export const CONTRACT_CHANGE_STOP = 'CONTRACT_CHANGE_STOP';

export const ADD_CONTRACTS_DETAILS = 'ADD_CONTRACTS_DETAILS';

// OLD

export const WEB3_INITIALIZED = 'WEB3_INITIALIZED';
export const INITIALIZE_WEB3 = 'INITIALIZE_WEB3';
